services:
  backstage:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    restart: unless-stopped
    ports:
      - "7007:7007"
      - "3000:3000"
    env_file:
      - .env