name: Build and Publish Dev Image to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # NOVO PASSO: Configurar o ambiente Node.js e Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a mesma versão Node que você usa localmente
          cache: 'yarn'

      # NOVO PASSO: Instalar as dependências do projeto
      - name: Install dependencies
        run: yarn install --immutable

      # NOVO PASSO: Compilar os artefatos do backend
      - name: Build backend artifacts
        run: yarn workspace backend build

      # Passo de Login (continua igual)
      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Passo de Metadados (continua igual)
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/backstage

      # Passo de Build e Push (continua igual, mas agora funcionará)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}